@NoteAppBackend_HostAddress = http://localhost:5022

GET {{NoteAppBackend_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{NoteAppBackend_HostAddress}}/api/notetypes/all
Accept: application/json

###

GET {{NoteAppBackend_HostAddress}}/api/notes/all
Accept: application/json

###

POST {{NoteAppBackend_HostAddress}}/api/notes
Content-Type: application/json
{
  "NoteTitle": "Notes from Dr. Miles Munroe",
  "NoteBody": "Motivation is an emotion, it is fickle and doesn't last...",
  "Date": "10/15/2025",
  "NoteTypeId": "" 
}

###